name: quiz
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  dart_console:
  excel:
  path:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
